export const articles = [
  {
    id: 1,
    name: 'Moonbeam Marigold',
    img: './media/images/catalog/moonbeam-marigold.png',
    category: 'Plants',
    price: '10',
  },
  {
    id: 2,
    name: 'Ember Echeveria',
    img: './media/images/catalog/ember-echeveria.png',
    category: 'Plants',
    price: '12',
  },
  {
    id: 3,
    name: 'Crimson Crassula',
    img: './media/images/catalog/crimson-crassula.png',
    category: 'Plants',
    price: '8',
  },
  {
    id: 4,
    name: 'Golden Gasteria',
    img: './media/images/catalog/golden-gasteria.png',
    category: 'Plants',
    price: '15',
  },
  {
    id: 5,
    name: 'Rainbow Rhipsalis',
    img: './media/images/catalog/rainbow-rhipsalis.png',
    category: 'Plants',
    price: '10',
  },
  {
    id: 6,
    name: 'Jade Jewel Orchid',
    img: './media/images/catalog/jade-jewel-orchid.png',
    category: 'Succulents',
    price: '25',
  },
  {
    id: 7,
    name: 'Midnight Moss',
    img: './media/images/catalog/midnight-moss.png',
    category: 'Succulents',
    price: '5',
  },
  {
    id: 8,
    name: 'Aquamarine Aloe',
    img: './media/images/catalog/aquamarine-aloe.png',
    category: 'Succulents',
    price: '15',
  },
];
